CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
    NOTIFICATION_ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    USER_ID UUID NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    TICKET_ID UUID REFERENCES TICKETS(TICKET_ID) ON DELETE SET NULL,
    TYPE VARCHAR(50) NOT NULL,
    TITLE VARCHAR(255),
    MESSAGE TEXT,
    IS_READ BOOLEAN DEFAULT FALSE,
    READ_AT TIMESTAMP WITH TIME ZONE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_NOTIFICATIONS_USER ON NOTIFICATIONS(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_NOTIFICATIONS_USER_READ ON NOTIFICATIONS(USER_ID, IS_READ);
CREATE INDEX IF NOT EXISTS IDX_NOTIFICATIONS_CREATED ON NOTIFICATIONS(CREATED_AT DESC);
